# Generated by Django 5.1.1 on 2024-09-07 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, message='Минимальная длина ппароля 3 символа')])),
            ],
        ),
    ]
