# Generated by Django 5.1.1 on 2024-09-09 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at_user_updated_at_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required field. 150 characters or fewer. Password must contain only letters, numbers and symbols @/./+/-/_.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Password must contain only letters, numbers and symbols @/./+/-/_.', regex='^[a-zA-Zа-яА-Я0-9+_@.-]*$'), django.core.validators.MaxLengthValidator(150, message='Max length is 150 characters')], verbose_name='Username'),
        ),
    ]
