# Generated by Django 5.1.1 on 2024-09-09 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Your password must contain at least 3 characters', validators=[django.core.validators.MinLengthValidator(3, message='Must be at least 3 characters')], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required field. 150 characters or fewer. Password must contain only letters, numbers and symbols @/./+/-/_.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid characters included', regex='^[a-zA-Zа-яА-Я0-9+_@.-]*$'), django.core.validators.MaxLengthValidator(150, message='Max length is 150 characters')], verbose_name='Username'),
        ),
    ]
