# Generated by Django 5.1.1 on 2024-09-18 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_status_created_at_alter_status_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_as_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_as_performer', to=settings.AUTH_USER_MODEL, verbose_name='Performer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
