# Generated by Django 5.1.1 on 2024-09-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_label_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='task_as_label', through='tasks.Membership', to='tasks.label', verbose_name='Labels'),
        ),
    ]
