# Generated by Django 5.1.1 on 2024-09-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_labels_task_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='label',
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='task_as_label', through='tasks.Membership', to='tasks.label', verbose_name='Labels'),
        ),
    ]
