# Generated by Django 5.1.1 on 2024-09-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_performer_task_executor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='title',
            new_name='name',
        ),
    ]
