# Generated by Django 5.1.1 on 2024-10-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0008_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='TaskLabels',
        ),
        migrations.AlterModelOptions(
            name='tasklabels',
            options={'verbose_name': 'task_label_membership', 'verbose_name_plural': 'task_label_memberships'},
        ),
    ]
